Epione/Controllers/MedecinFController.cs
using Domain;
using ServiceEpione;
using System;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Epione.Controllers
{
    [Authorize(Roles = "Medecin")]
    public class MedecinFController : Controller
    {
        UserService us = new UserService();
        PatientService Ps = new PatientService();

        // GET: PatientF
        public ActionResult Index(string searchBy, string search)
        {
         
            var users = Ps.GetAll();
            List<Patient> y = new List<Patient>();

            foreach (var item in users)
            {

                if (item.idSocial.ToString() != null) { 
                y.Add(
                    
                    new Patient
                    {   
                        Id = item.Id,
                        Email = item.Email,
                        FirstName = item.FirstName,
                        LastName = item.LastName,
                        PhoneNumber = item.PhoneNumber,
                        UserName = item.UserName,                    
                    });
            }
            }
            //List<User> a = y.Where(x => x.Roles.Where(p => Roles.GetUsersInRole("Patient"))).ToList();


            if (searchBy == "Email")
            {
                return View(y.Where(x => x.Email.StartsWith(search) || search == null).ToList());
            }
            else if (searchBy == "UserName")
            {
                return View(y.Where(x => x.UserName.StartsWith(search) || search == null).ToList());
            }else
            {
                return View(y);
            }
      
        }








        public ActionResult IndexJson(string searchBy, string search)
        {

            var users = Ps.GetAll();
            List<Patient> y = new List<Patient>();

            foreach (var item in users)
            {

                if (item.idSocial.ToString() != null)
                {
                    y.Add(

                        new Patient
                        {
                            Id = item.Id,
                            Email = item.Email,
                            FirstName = item.FirstName,
                            LastName = item.LastName,
                            PhoneNumber = item.PhoneNumber,
                            UserName = item.UserName,
                        });
                }
            }
            //List<User> a = y.Where(x => x.Roles.Where(p => Roles.GetUsersInRole("Patient"))).ToList();


           
         
                return Json(y, JsonRequestBehavior.AllowGet);


            

        }












        // GET: PatientF/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PatientF/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PatientF/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: PatientF/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PatientF/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: PatientF/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PatientF/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Epione/Controllers/ParcoursController.cs
using Domain;
using Domaine;
using Epione.Models;
using ServiceEpione;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Net.Mail;
using System.Net;
using DATA;

namespace Epione.Controllers
{
    [Authorize(Roles = "Medecin")]
    public class ParcoursController : Controller
    {
        //////////////////////////////////////////////////////////////////////
        UserService us = new UserService();
        public string FindMailOfUserById(int id)
        {

            string y = us.GetById(id).Email;
            return y;
        }
        public string FindPasswordOfUserById(int id)
        {

            string y = us.GetById(id).Password;
            return y;
        }
        public string FindFirstNameOfUserById(int id)
        {

            string y = us.GetById(id).FirstName;
            return y;
        }
        public string FindLastNameOfUserById(int id)
        {

            string y = us.GetById(id).LastName;
            return y;
        }
       


        //////////////////////////////////////////////////////////////////////
        ParcoursService ps = new ParcoursService();
        public Parcours FindParcoursById(int id)
        {
            Parcours y = ps.GetById(id);
            return y;
        }

        public  ActionResult ChangeEtat(int idParcours,ParcoursModel pm,int idPatientt)
        {
            var parcourrs = new Parcours { id = idParcours,Etatrdv="Consultation terminée" };
            using (var db = new MyContext())
            {
                db.parcours.Attach(parcourrs);
                db.Entry(parcourrs).Property(x => x.Etatrdv).IsModified = true;
                db.SaveChanges();
            }
            Parcours p = new Parcours();
            p.idPatient = pm.idPatient = idPatientt;

            return RedirectToAction("Index", new
            {
                idPatientt = pm.idPatient
            });

        }

    // GET: Parcours
    public ActionResult Index(int idPatientt)
        {
            var parcours = ps.GetAll();

            List<ParcoursModel> fVM = new List<ParcoursModel>();
           
            foreach (var item in parcours)
            {

                fVM.Add(
                    new ParcoursModel
                    {
                        NomMedecin = item.NomMedecin,
                        Specialite = item.Specialite,
                        id = item.id,
                        Maladie = item.Maladie,
                        date = item.date,
                        Etat = item.Etat,
                        Justification = item.Justification,
                        Adresse = item.Adresse,
                        idPatient = item.idPatient,
                        idMedecin = item.idMedecin,
                        idRDV = item.idRDV,
                        Etatrdv = item.Etatrdv,
                    });
            }
            List<ParcoursModel> fVm2 =fVM.Where(par => par.idPatient == idPatientt).ToList();
            return View(fVm2);
        }



        public JsonResult IndexJson(int idPatientt)
        {
            var parcours = ps.GetAll();

            List<ParcoursModel> fVM = new List<ParcoursModel>();

            foreach (var item in parcours)
            {

                fVM.Add(
                    new ParcoursModel
                    {
                        NomMedecin = item.NomMedecin,
                        Specialite = item.Specialite,
                        id = item.id,
                        Maladie = item.Maladie,
                        date = item.date,
                        Etat = item.Etat,
                        Justification = item.Justification,
                        Adresse = item.Adresse,
                        idPatient = item.idPatient,
                        idMedecin = item.idMedecin,
                        idRDV = item.idRDV,
                        Etatrdv = item.Etatrdv,
                    });
            }
            List<ParcoursModel> fVm2 = fVM.Where(par => par.idPatient == idPatientt).ToList();
            return Json(fVM, JsonRequestBehavior.AllowGet);
        }














        // GET: Parcours/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Parcours/Create
        public ActionResult Create(int idPatientt, ParcoursModel pm)
        {
            Parcours p = new Parcours();
            p.idPatient = pm.idPatient=idPatientt;
            return View(new ParcoursModel() { date = DateTime.Now ,idPatient=idPatientt,idMedecin = Int32.Parse(System.Web.HttpContext.Current.User.Identity.GetUserId()),idRDV=0,Etatrdv="Pas encore"});
        }

        // POST: Parcours/Create
        [HttpPost]
        public ActionResult Create(ParcoursModel pm)
        {
            Parcours p = new Parcours();
            if (ModelState.IsValid)
            {
                p.NomMedecin = pm.NomMedecin;
                p.Specialite = pm.Specialite;
                p.id = pm.id;
                p.Maladie = pm.Maladie;
                p.date = pm.date;
                p.Etat = pm.Etat;
                p.Justification = pm.Justification;
                p.Adresse = pm.Adresse;
                p.idPatient = pm.idPatient;
                p.idMedecin = pm.idMedecin;
                p.idRDV = pm.idRDV;
                p.Etatrdv = pm.Etatrdv;
                ps.Add(p);
                ps.Commit();

                
                /////////////////////

                var senderemail = new MailAddress(FindMailOfUserById(Int32.Parse(System.Web.HttpContext.Current.User.Identity.GetUserId())), "Recommandation Spécialiste");
                var receiveremail = new MailAddress(FindMailOfUserById(p.idPatient), "Receiver");
                var password = FindPasswordOfUserById(Int32.Parse(System.Web.HttpContext.Current.User.Identity.GetUserId()));
                var sub = "Un rendez-vous";
               
                var body = string.Concat("Bonjour je suis votre Docteur Mr/Mme "+ FindFirstNameOfUserById(Int32.Parse(System.Web.HttpContext.Current.User.Identity.GetUserId()))+" "+ FindLastNameOfUserById(Int32.Parse(System.Web.HttpContext.Current.User.Identity.GetUserId()))+" , je voulais vous informer que je vous ai planifié un nouveau rendez-vous avec "+ Request["NomMedecin"].ToString() +" Spécialisé en "+ Request["Specialite"].ToString() + " veuillez consulter votre parcours et merci d'attendre la confirmation du docteur que je vous ai recommandé");
                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(senderemail.Address, password)

                };
                using (var mess = new MailMessage(senderemail, receiveremail)
                {
                    Subject = "Proposition Rendez-vous",
                    Body = body
                })
                {
                    smtp.Send(mess);
                }
                /////////////////////

                return RedirectToAction("Index", new
                {
                    idPatientt = pm.idPatient
                });

            }
            return View(p);

        }

        // GET: Parcours/Edit/5
        public ActionResult Edit(int idPatientt,int id, ParcoursModel pm)
        {
            Parcours p = new Parcours();
            p.idPatient = pm.idPatient = idPatientt;
            return View(new ParcoursModel() { date = DateTime.Now, idPatient = idPatientt, idMedecin = Int32.Parse(System.Web.HttpContext.Current.User.Identity.GetUserId()),idRDV=0,Etatrdv="Pas encore" });
        }

        // POST: Parcours/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ParcoursModel pm)
        {
            try
            {
                Parcours parcourss = ps.GetById(id);
                parcourss.NomMedecin = pm.NomMedecin;
                parcourss.Specialite = pm.Specialite;
                parcourss.id = pm.id;
                parcourss.Maladie = pm.Maladie;
                parcourss.date = pm.date;
                parcourss.Etat = pm.Etat;
                parcourss.Justification = pm.Justification;
                parcourss.Adresse = pm.Adresse;
                parcourss.idPatient = pm.idPatient;
                parcourss.idMedecin = pm.idMedecin;
                parcourss.idRDV = pm.idRDV;
                parcourss.Etatrdv = pm.Etatrdv;
                ps.Update(parcourss);
                ps.Commit();
            }
            catch (DataException/* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                return RedirectToAction("Edit", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index", new
            {
                idPatientt = pm.idPatient
            });
        }

        // GET: Parcours/Delete/5
        public ActionResult Delete(int idPatientt, int id,ParcoursModel pm)
        {
            Parcours p = new Parcours();
            p.idPatient = pm.idPatient = idPatientt;
            return View(new ParcoursModel() { idPatient = idPatientt });
        }

        // POST: Parcours/Delete/5
        [HttpPost]
        public ActionResult Delete(int id,FormCollection collection, ParcoursModel pm)
        {
            {
                try
                {
                    Parcours parcourss = ps.GetById(id);
                    parcourss.NomMedecin = pm.NomMedecin;
                    parcourss.Specialite = pm.Specialite;
                    parcourss.id = pm.id;
                    parcourss.Maladie = pm.Maladie;

Epione/Views/MedecinF/Index.cshtml
 @model IEnumerable<Domain.User>
@{
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Affichage Parcours</title>

    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="~/Content/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="~/Content/css/animate.css" rel="stylesheet">
    <link href="~/Content/css/style.css" rel="stylesheet">
</head>
<body>
    
    <div class="col-lg-12">
        <div class="ibox float-e-margins">       
            <div class="ibox-content">
                <div class="row">
                    <div class="col-sm-3">
                        <p>
                            @using (@Html.BeginForm("Index", "MedecinF", FormMethod.Get))
                            {
                                <b>Recherche Par:</b>
                                @Html.RadioButton("searchBy", "Email", true) <text>Email</text>
                                @Html.RadioButton("searchBy", "UserName") <text>UserName</text><br />
                                @Html.TextBox("search") <input type="submit" value="Rechercher" class="btn btn-sm btn-primary" height="10" />
                            }
                        </p>
                    </div>
                </div>
                <div class="table-responsive">
                 
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Email)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LastName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PhoneNumber)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.UserName)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LastName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserName)
                                </td>
                                <td>
                                    @Html.ActionLink("Affichage Rendez-vous", "Index", "Parcours", new { idPatientt = item.Id }, null)
                                </td>
                            </tr>
                        }

                    </table>

                </div>

            </div>
        </div>
    </div>
</body>
</html>

Epione/Views/MedecinF/IndexJson.cshtml
@model Domain.Patient

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>IndexJson</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>