Epione/Controllers/MedecinController.cs
using DATA;
using Models;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using Domain;

namespace Epione.Controllers
{
   // [Authorize(Roles ="Medecin")]
    public class MedecinController : Controller
    {

        MedecinService MS;
        public MedecinController()
        {
            MS = new MedecinService(); 
        }
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }

        // GET: Default/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Default/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Default/Create
        [HttpPost]
        public ActionResult CreatePlus(PlusMed PlusModel ,  FormCollection collection)
        {





            global::Models.PlusMed f = new global::Models.PlusMed();

            f.specialieProfondu = PlusModel.specialieProfondu;
            
            f.IDMed = PlusModel.IDMed;
            f.Hopital = PlusModel.Hopital; 

            MS.Add(f);
            MS.Commit();
            return RedirectToAction("index");


            //try
            //{
            //    // TODO: Add insert logic here

            //    return RedirectToAction("Index");
            //}
            //catch
            //{
            //    return View();
            //}
        }

        // GET: Default/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Default/Edit/5
    
        [HttpPost]
        public ActionResult Edit(PlusMed PlusModel, int id , FormCollection collection)
        {




            global::Models.PlusMed f = new global::Models.PlusMed();

            f.specialieProfondu = PlusModel.specialieProfondu;
            f.ID = id; 
            f.IDMed = PlusModel.IDMed;
            f.Hopital = PlusModel.Hopital;

            MS.add(f);
            MS.Commit();
            return RedirectToAction("index");











            //try
            //{
            //    // TODO: Add update logic here

            //    return RedirectToAction("Index");
            //}
            //catch
            //{
            //    return View();
            //}
        }

        // GET: Default/Delete/5
        public ActionResult Delete( int id)
        {

          
            return RedirectToAction("index");
        }

        // POST: Default/Delete/5
        [HttpPost]
        public ActionResult Delete(PlusMed PlusModel, int id, FormCollection collection)
        {

            global::Models.PlusMed f = new global::Models.PlusMed();

            f.specialieProfondu = PlusModel.specialieProfondu;
            f.ID = id;
            MS.Delete(f);
            MS.Commit();
            return RedirectToAction("index");


            //try
            //{
            //TODO: Add delete logic here

            //    return RedirectToAction("Index");
            //}
            //catch
            //{
            //    return View();
           }
         public ActionResult Index1(string firstname, string lastname, string specialite, string localisation)
        {
            int page = 1;
            string sortdir = "asc";
            string sort = "FirstName";
            int pageSize = 10;
            int totalRecord = 0;
            if (page < 1) page = 1;
            int skip = (page * pageSize) - pageSize;
            // Parameter
            //ViewBag.last, ViewBag.first, ViewBag.spec, ViewBag.localisation, sort, sortdir, skip, pageSize
            var data = GetMedecin(firstname, lastname , specialite, localisation);
            ViewBag.TotalRows = totalRecord;
            //ViewBag.search = search;
            return View(data);
        }

        public ActionResult GetMedecins()
        {
            List<Medecin> list = new List<Medecin>();
           // list = this.GetMedecin();
            return View(list);

        }

        //string firstname, string lastname, string localisation, string specialite, string sort, string sortdir, int skip, int pageSize
        public List<Medecin> GetMedecin(string firstname, string lastname, string specialite, string localisation)
        {

            //using (MyContext dc = new MyContext())
            //{
            //    var v = (from a in dc.Medecin
            //             where
            //                     a.FirstName.Contains(firstname) ||
            //                     a.LastName.Contains(lastname) ||
            //                     a.localisation.Contains(localisation) ||
            //                     a.specialite.Contains(specialite)
            //             //  a.specialite.Contains(search)
            //             select a
            //                    );
            // totalRecord = v.Count();
            // v = v.OrderBy(sort + " " + sortdir);
            //    if (pageSize > 0)
            //    {
            //        v = v.Skip(skip).Take(pageSize);
            //    }

            //    var x = v.ToList();
            //   return v.ToList();

            MyContext dc = new MyContext();
            List<Medecin> myList = new List<Medecin>();
            myList = firstname == "" && lastname != "" && localisation != "" && specialite != "" ? dc.Medecin
                .Where(item => item.LastName == lastname && item.specialite == specialite && item.localisation == localisation).ToList() :

                lastname == "" && firstname != "" && localisation != "" && specialite != "" ? dc.Medecin
                .Where(item => item.FirstName == firstname && item.specialite == specialite && item.localisation == localisation).ToList() :

                specialite == "" && firstname != "" && localisation != "" && lastname != "" ? dc.Medecin
                .Where(item => item.LastName == lastname && item.FirstName == firstname && item.localisation == localisation).ToList() :

                localisation == "" && firstname != "" && lastname != "" && specialite != "" ? dc.Medecin
                .Where(item => item.LastName == lastname && item.specialite == specialite && item.FirstName == firstname).ToList() :

                 firstname == "" && lastname == ""  && localisation != "" && specialite != "" ?
            dc.Medecin
                .Where(item => item.specialite == specialite && item.localisation == localisation).ToList() :
            localisation == "" && specialite == "" && firstname != "" && lastname != "" ? dc.Medecin
                .Where(item => item.FirstName == firstname && item.LastName == lastname).ToList() :
                localisation == "" && lastname == "" && specialite != "" && firstname != "" ?
            dc.Medecin
                .Where(item => item.specialite == specialite && item.FirstName == firstname).ToList() :
                firstname == "" && localisation == "" && lastname != "" && specialite != "" ?
            dc.Medecin
                .Where(item => item.specialite == specialite && item.LastName == lastname).ToList() :
                firstname == "" && specialite == "" && localisation != "" && lastname != "" ?
            dc.Medecin
                .Where(item => item.localisation == localisation && item.LastName == lastname).ToList() :
                specialite == "" && lastname == "" && localisation != "" && firstname != "" ?
            dc.Medecin
                .Where(item => item.FirstName == firstname && item.localisation == localisation).ToList() :

                dc.Medecin
                .Where(item => item.FirstName == firstname && item.localisation == localisation && item.LastName == lastname && item.specialite == specialite).ToList();

            //myList = dc.Medecin.Where(item => item.FirstName ==firstname)
            //    .ToList();

            return myList;
            }
        }

    }

Epione/Controllers/RDVController.cs
using Domain;
using Epione.Models;
using Microsoft.AspNet.Identity;
using Models;
using ServiceEpione;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Epione.Controllers
{
    public class RDVController : Controller
    {



        RDVService Rod = new RDVService();
        // GET: RDV


        public ActionResult Index()
        {

            var ress = Rod.GetAll();

            List<RDVModels> mvp = new List<RDVModels>();
            foreach (var item in ress)
            {
                if (item.idPatient == Int32.Parse(System.Web.HttpContext.Current.User.Identity.GetUserId()))
                {
                    mvp.Add(
                        new RDVModels
                        {
                            id = item.id,
                            nom = item.nom,
                            prenom = item.prenom,
                            date = item.date,
                            ville = item.ville,
                            maladi = item.maladi,


                        });
                }
            }
            return View(mvp);
        }



        // GET: RDV/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RDV/Create
        public ActionResult Create()
        {
            RDVModels rd = new RDVModels();
            return View(rd);
        }

        // POST: RDV/Create
        [HttpPost]
        public ActionResult Create(RDVModels Rd , int id1)
        {
            try
            {
                RDV r = new RDV
                {
                    date = Rd.date,
                    maladi = Rd.maladi,
                    nom = Rd.nom,
                    prenom = Rd.prenom,
                    ville = Rd.ville,
                    id = Rd.id ,
                    idMedecin = id1 ,
                    idPatient = 41 , 
                };

                Rod.Add(r);
                Rod.Commit();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RDV/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RDV/Edit/5







        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, RDV R)
        {
            try
            {
                Domain.RDV ress = Rod.GetById(id);
                ress.nom = R.nom;
                ress.prenom = R.prenom;
                ress.date = R.date;
                ress.ville = R.ville;
                ress.maladi = R.maladi;

                Rod.add(ress);
                Rod.Commit();
                return RedirectToAction("Index");

            }
            catch
            {
                return View();

            }
        }


        // GET: RDV/Delete/5
        public ActionResult Delete(int id)
        {
            var d = Rod.GetById(id);
            Rod.Delete(d);
            Rod.Commit();
            return Redirect(Request.UrlReferrer.ToString());
        }

        // POST: RDV/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


       

        
        public ActionResult Mail()
        {
           
            return View();
        }
        [HttpPost]

        public ActionResult Mail(MailViewModel mvm)
        {


            MailMessage mail = new MailMessage("EpionePidev@esprit.tn", mvm.Reciever, mvm.Subject, mvm.Message);
            mail.IsBodyHtml = true;
            SmtpClient smtpClient = new SmtpClient("Smtp.gmail.com", 587);
            smtpClient.EnableSsl = true;

            smtpClient.Credentials = new System.Net.NetworkCredential("EpionePidev@gmail.com", "epionepidev123");
            smtpClient.Send(mail);
            //!MAIL

            //!MAIL
            return View();
        }
        //MAIL





    }

}

Epione/Views/Medecin/Agenda.cshtml
@{
    ViewBag.Title = "Index";
}


@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<h2>Index</h2>
<div id="calender"></div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><span id="eventTitle"></span></h4>
            </div>
            <div class="modal-body">
                <p id="pDetails"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<link href="~/Content/cal/fullcalendar.min.css" rel="stylesheet" />
<link href="~/Content/cal/fullcalendar.print.css" rel="stylesheet" media="print" />

@section Scripts{
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
<script src="~/Content/cal/fullcalendar.min.js"></script>

    <script>
        $(document).ready(function () {
            var events = [];
            $.ajax({
                type: "GET",
                url: "/Medecin/GetEvents",
                success: function (data) {
                    $.each(data, function (i, v) {
                        events.push({
                            title: v.maladi,
                            description: v.ville,
                          //  DateDebutR: moment(v.DateDebutR),
                           // DateFinR: v.DateFinR != null ? moment(v.DateFinR) : null,
                            start: moment(v.DateDebutR),
                            end: v.DateFinR != null ? moment(v.DateFinR) : null,
                            color: '#378006',
                            allDay: true
                        });
                    })

                    GenerateCalender(events);
                },
                error: function (error) {
                    alert('failed');
                }
            })

            function GenerateCalender(events) {
                $('#calender').fullCalendar('destroy');
                $('#calender').fullCalendar({
                    contentHeight: 400,
                    defaultDate: new Date(),
                    timeFormat: 'DD-MM-YYYY hh:mm',
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'month,basicWeek,basicDay,agenda'
                    },
                    eventLimit: true,
                    eventColor: '#378006',
                    events: events,
                    eventClick: function (calEvent, jsEvent, view) {
                        $('#myModal #eventTitle').text(calEvent.title);
                        var $description = $('<div/>');
                        $description.append($('<p/>').html('<b>Start:</b>' + calEvent.start.format('DD-MM-YYYY hh:mm')));
                        if (calEvent.end != null) {
                            $description.append($('<p/>').html('<b>End:</b>' + calEvent.end.format('DD-MM-YYYY hh:mm')));
                        }
                        $description.append($('<p/>').html('<b>Description:</b>' + calEvent.description));
                        $('#myModal #pDetails').empty().html($description);

                        $('#myModal').modal();
                    }
                })
            }
        })
    </script>
}

Epione/Views/Medecin/Create.cshtml
@model Domain.PlusMed
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm("CreatePlus", "Medecin", FormMethod.Post, new { enctype = "multipart/form-data" })) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>PlusMed</h4>
            <hr />
            
            
            
            <div class="form-group">
                @Html.LabelFor(model => model.IDMed, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IDMed, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IDMed, "", new { @class = "text-danger" })
                </div>
            </div>

            
            
            
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.specialieProfondu, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.specialieProfondu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.specialieProfondu, "", new { @class = "text-danger" })
                </div>
            </div>
    
            
            
            
            
            
            <div class="form-group">
                @Html.LabelFor(model => model.Hopital, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Hopital, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Hopital, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Epione/Views/Medecin/Delete.cshtml
@model Domain.PlusMed

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>PlusMed</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.IDMed)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IDMed)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.specialieProfondu)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.specialieProfondu)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Hopital)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Hopital)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Epione/Views/Medecin/Details.cshtml
@model Models.PlusMedModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>PlusMedModel</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.IDMed)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IDMed)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.specialieProfondu)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.specialieProfondu)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Hopital)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Hopital)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.image)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.image)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Epione/Views/Medecin/Edit.cshtml
@model Domain.PlusMed

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>PlusMed</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.IDMed)

            <div class="form-group">
                @Html.LabelFor(model => model.IDMed, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IDMed, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IDMed, "", new { @class = "text-danger" })
                </div>
            </div>

    
            <div class="form-group">
                @Html.LabelFor(model => model.specialieProfondu, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.specialieProfondu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.specialieProfondu, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Hopital, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Hopital, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Hopital, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Epione/Views/Medecin/Index.cshtml
    
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}




<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />


</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
          
            <th>
                IDMED
            </th>
            <th>
                Specialité
            </th>
            <th>
               Hopitale
            </th>
            <th>
                Image
            </th>
            <th></th>
        </tr>
    
        @{


            var emp = (Domain.PlusMed)ViewData["plus"];//retrive Data from ViewData or ViewBag
        }






        <tr>
            <td>
                @emp.IDMed
            </td>
            <td>
                @emp.Hopital
            </td>
            <td>
                @emp.specialieProfondu
            </td>
        </tr>
    }
    
    </table>



</body>
</html>

Epione/Views/Medecin/Index1.cshtml
@model IEnumerable<Domain.Medecin>
@{
    Layout = null;
    var grid = new WebGrid(canPage: true, rowsPerPage: 10);
    grid.Bind(source: Model, rowCount: ViewBag.TotalRows, autoSortAndPage: false);
}

<!DOCTYPE html>

@{
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <h2> Liste des Medecins</h2>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                </div>
                <div class="collapse navbar-collapse">
                   
                    

                     @using (Html.BeginForm("index1", "Medecin", FormMethod.Get, new { @class = "navbar-form navbar-left" }))
                    {
                        <div class="form-group">
                            <input type="text" name="firstname"  class="form-control" placeholder="First name" />
                            <input type="text" name="lastname"  class="form-control" placeholder="Last name" />
                            <input   class="form-control" type="text" name="specialite"   placeholder="Specialite" />.
                               
                            <input type="text" name="localisation"  class="form-control" placeholder="Ou ? (Region ou Ville)" />
                        </div>
                        <button type="submit" value="Search" class="btn btn-success">Search</button>
                    }



                </div>
            </div>
        </nav>
        @*<div>
            @grid.Table(
                tableStyle: "table table-responsive table-bordered",
                columns: grid.Columns(
                    grid.Column(columnName: "FirstName", header: "First Name"),
                    grid.Column(columnName: "LastName", header: "Last Name"),
                    grid.Column(columnName: "localisation", header: "localisation"),
                    grid.Column(columnName: "specialite", header: "specialite")
                    
                )
            )

            <div class="row">
                <div class="col-sm-6">

                    @grid.PagerList(mode: WebGridPagerModes.All, paginationStyle: "pagination pagination-small pagination-right")
                </div>
            </div>

            @Html.Hidden("dir", grid.SortDirection)
            @Html.Hidden("col", grid.SortColumn)

        </div>*@
        <div>
            @{

                if (Model.Count() == 0)
                {
                    <h1>Veuiller saisir vos critère de recherche</h1>
                }
                else
                {<table class="table table-hover">
                    <tr>
                        <th class="bg-primary text-white">FirstName</th>
                        <th class="bg-primary text-white">LastName</th>
                        <th class="bg-primary text-white">localisation</th>
                        <th class="bg-primary text-white">specialite</th>
                        <th class="bg-primary text-white"></th>
                        <th class="bg-primary text-white"></th>
                        <th class="bg-primary text-white"></th>
                    </tr>
                    @foreach (var i in Model.ToList())
                    {
                        <tr>
                            <td style="display: none ; ">@i.Id</td>
                            
                            <td>@i.FirstName</td>
                            <td>@i.LastName</td>
                            <td>@i.localisation</td>
                            <td>@i.specialite</td>
                            <td>
                                <div class="btn-group btn-group-lg">
                                    <a href="@Url.Action("Create","RDV" , new { id1= @i.Id })" type="button" class="btn btn-primary">Prendre un RDV</a>
                                    <button type="button" class="btn btn-primary">Appeller</button>
                                    <a href="@Url.Action("Mail","RDV")" type="button" class="btn btn-primary">E-mail</a>
                                </div>
                            </td>
                        </tr>
                    }
                </table>
                }


                }




</div>

     
</div>
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script>
        $(function () {
            try {
                var dir = $('#dir').val();
                var col = $('#col').val();
                var header = $("th a[href*=" + col + "]");
                if (dir == "Ascending") {
                    header.text(header.text() + "  ▲")
                }
                if (dir == "Descending") {
                    header.text(header.text() + "  ▼");
                }

            } catch (e) {

            }
        })
    </script>
</body>
</html>

Epione/Views/Medecin/date.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>date</title>
</head>






<body>
 




        @using (Html.BeginForm("date", "Medecin", FormMethod.Post))
        {

            <table >
                <tr>
                    <td>
                        <input id="date1" type="datetime" name="DateDeb" placeholder="debut"   style=" width: 100%;
    padding: 12px 80px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;" />
                    </td>
                </tr>

                <tr>
                    <td>
                        <input id="date2" type="datetime" name="DateFin" placeholder="fin" style=" width: 100%;
    padding: 12px 80px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;" 
                               />
                    </td>
                </tr>
    
                
                @{


                    var emp = ViewData["id"];//retrive Data from ViewData or ViewBag
                }







                            <input  name="id1" type="hidden" value= @emp  >

                <tr>
                    <td>
                        <button type="submit" value="submit" class="btn btn-primary">save</button>
                    </td>
                </tr>


                <tr>

                    <td>
                        <strong><p id="p2">le couleur indique l état</p></strong>
                    </td>

                </tr>

            </table>
        }






    <script type="text/javascript">

	function date() {
		// body...
var date11 = document.getElementById("date1").value ;


var date12 = document.getElementById("date2").value ;


if(date11<=date12)
{

	document.getElementById("p2").style.color = "green";

}



if(date11>date12)
{

	document.getElementById("p2").style.color = "red";
}

	}



    </script>

</body>
</html>